language: shell
matrix:
  include:
  - name: Build on Ubuntu 16.04
    os: precise
    before_install:
    - chmod +x .travis/build.sh
    install:
    - "./.travis/build.sh"
deploy:
  provider: releases
  api_key:
    secure: AqCWxjc6Yw04eTn7bbRtNR/rrtpglzluBdEVra2CfUC12c6rIzYA8jEFqdPtHV17w9pTpinRXYlQoixBfxtjENV/33Pls+GjKR59S13BTACMgqRt1t06xJy5iq0lZo7EcGIWOYx27Hn4eDWTjqQaHV1rr05Gm5h9ON7KYVfaoPs/VnD4Pwb0kAKqz8zwtDypZMVoEAUARny7lpRKJpOET1DKB7WHkr/UQY8DkGe99QxJJXfgPNjPifhjojSvPGEAtw61R7NSJQRnFPozKM8oAmIJc/RFvZNh2lKgajTHRpdTo+YniLDLjL/YKjQPsG9hsver9QnSMUA6/FCb5rq0lryhHz/ZWXlWlN+a0InpMvPzMET+UVpCa0jPTk6lsGK8Y1SZ937uSvrQX4bDiPWhFneXzFHbqScyHt+67Rghq1ego4TQCNUiu0Uo7iXh1Fi6ZsAeMK1LoBWi9j4d65NXwqpAkvvrupjqxHXNNrZIWCi8ZUHgw35Gxf2tkpC7T9849lWFsQq2T5iXUNJm9usKr0/v+q0Yg3ogY7+Dasxu6IE4zGLwkM+Pa4YOe4RLBdNnDEe1iqDq951koLTvLNi+pbZ7hzJt6QwGm8rNEeAtXiJq8FrA/h917KTpY/3c1EoWkKV6M/XIltfQDhyHQP5ra0P58RySMu/xrdjKYXGw5pA=
  skip_cleanup: true
  file_glob: true
  file: dist/*.jar
  on:
    repo: wrvenkat/burp-multistep-csrf-poc
